# Generated by Django 6.0.7 on 2026-08-04 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ምድብ')),
                ('amharic_name', models.CharField(blank=True, max_length=100, verbose_name='የአማርኛ ስም')),
                ('description', models.TextField(blank=True, verbose_name='መግለጫ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ምድብ',
                'verbose_name_plural': 'ምድቦች',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='የደብዳቤው ርዕስ')),
                ('reference_number', models.CharField(max_length=100, unique=True, verbose_name='የደብዳቤ ቁጥር')),
                ('doc_type', models.CharField(choices=[('INCOMING', 'ገቢ ደብዳቤ'), ('OUTGOING', 'ወጪ ደብዳቤ'), ('INTERNAL', 'የውስጥ ማስታወሻ')], max_length=10, verbose_name='ዓይነት')),
                ('sender', models.CharField(max_length=255, verbose_name='ላኪ')),
                ('receiver', models.CharField(max_length=255, verbose_name='ተቀባይ')),
                ('description', models.TextField(blank=True, verbose_name='መግለጫ / ማስታወሻ')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/', verbose_name='ፋይል (PDF/Image)')),
                ('status', models.CharField(choices=[('PENDING', 'በመጠባበቅ ላይ'), ('IN_PROGRESS', 'በሂደት ላይ'), ('COMPLETED', 'ተጠናቋል'), ('ARCHIVED', 'ተቀምጧል')], default='PENDING', max_length=15, verbose_name='ሁኔታ')),
                ('priority', models.CharField(choices=[('LOW', 'ዝቅተኛ'), ('MEDIUM', 'መካከለኛ'), ('HIGH', 'ከፍተኛ'), ('URGENT', 'አስቸኳይ')], default='MEDIUM', max_length=10, verbose_name='ቅድሚያ')),
                ('date_received', models.DateField(blank=True, null=True, verbose_name='የደረሰበት ቀን')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='የመጨረሻ ቀን')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='የተመዘገበበት ቀን')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ዝመና')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='የወረዱ ብዛት')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='የታዩ ብዛት')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_documents', to=settings.AUTH_USER_MODEL, verbose_name='የተመደበለት')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.category', verbose_name='ምድብ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_created', to=settings.AUTH_USER_MODEL, verbose_name='የተመዘገበው')),
            ],
            options={
                'verbose_name': 'ደብዳቤ',
                'verbose_name_plural': 'ደብዳቤዎች',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='እርምጃ')),
                ('detail', models.TextField(blank=True, verbose_name='ዝርዝር')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='ጊዜ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='documents.document')),
            ],
            options={
                'verbose_name': 'የእንቅስቃሴ ታሪክ',
                'verbose_name_plural': 'የእንቅስቃሴ ታሪኮች',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InnovationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ርዕስ')),
                ('description', models.TextField(verbose_name='መግለጫ')),
                ('status', models.CharField(choices=[('PLANNING', 'ዕቅድ ላይ'), ('ACTIVE', 'በሂደት'), ('COMPLETED', 'ተጠናቋል'), ('ON_HOLD', 'ቆሟል')], default='PLANNING', max_length=12)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_projects', to=settings.AUTH_USER_MODEL, verbose_name='ኃላፊ')),
            ],
            options={
                'verbose_name': 'የፈጠራ ፕሮጀክት',
                'verbose_name_plural': 'የፈጠራ ፕሮጀክቶች',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='መልዕክት')),
                ('link', models.CharField(blank=True, max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ማሳወቂያ',
                'verbose_name_plural': 'ማሳወቂያዎች',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='የሥልጠና ርዕስ')),
                ('description', models.TextField(blank=True)),
                ('trainer', models.CharField(blank=True, max_length=150, verbose_name='አሠልጣኝ')),
                ('date', models.DateField(verbose_name='ቀን')),
                ('duration', models.PositiveIntegerField(default=1, verbose_name='ቀናት')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(blank=True, related_name='trainings', to=settings.AUTH_USER_MODEL, verbose_name='ተሳታፊዎች')),
            ],
            options={
                'verbose_name': 'ሥልጠና',
                'verbose_name_plural': 'ሥልጠናዎች',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'አስተዳዳሪ'), ('REGISTRAR', 'ሰናዳ'), ('VIEWER', 'ተመልካች')], default='VIEWER', max_length=12)),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='ክፍል / ቢሮ')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='ስልክ ቁጥር')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'የተጠቃሚ መረጃ',
                'verbose_name_plural': 'የተጠቃሚዎች መረጃ',
            },
        ),
    ]
