# Generated by Django 6.0.7 on 2026-09-04 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentForward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_department', models.CharField(blank=True, max_length=100, verbose_name='ወደ ቢሮ')),
                ('note', models.TextField(blank=True, verbose_name='ማስታወሻ')),
                ('is_read', models.BooleanField(default=False, verbose_name='ታይቷል')),
                ('forwarded_at', models.DateTimeField(auto_now_add=True, verbose_name='የተላከበት ቀን')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwards', to='documents.document', verbose_name='ደብዳቤ')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_docs', to=settings.AUTH_USER_MODEL, verbose_name='ላካ')),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_forwards', to=settings.AUTH_USER_MODEL, verbose_name='ተቀባይ')),
            ],
            options={
                'verbose_name': 'ደብዳቤ ማስተላለፍ',
                'verbose_name_plural': 'ደብዳቤ ማስተላለፍዎች',
                'ordering': ['-forwarded_at'],
            },
        ),
    ]
